### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-content-trust#84]
### Summary

Placeholder for `conda-content-trust 0.2.0` release.

| Pilot | @kenodegard |
|---|---|
| Co-pilot | @dholth |

### Tasks

[milestone]: https://github.com/conda/conda-content-trust/milestone/<milestone>
[process]: https://github.com/conda/conda-content-trust/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-content-trust/releases
[AnacondaRecipe]: https://github.com/AnacondaRecipes/conda-content-trust-feedstock
[conda-forge]: https://github.com/conda-forge/conda-content-trust-feedstock

#### The week before release week

- [x] Create release branch (named `0.2.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-content-trust-0.2.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    - @kenodegard tested `conda-content-trust 0.2.0` + `conda 23.7.3` works
    - @kenodegard tested `conda-content-trust 0.2.0` + `conda devenv` works

#### Release week

- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-content-trust/pull/88
- [x] https://github.com/conda/conda-content-trust/releases/tag/0.2.0
- [x] https://github.com/conda/conda-content-trust/pull/89
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-content-trust-feedstock/pull/2
    - [x] https://github.com/conda-forge/conda-content-trust-feedstock/pull/1
    
- [x] Hand off to the Anaconda packaging team
